options:
  logging: CLOUD_LOGGING_ONLY
steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-f',
        'dockerfiles/server.dockerfile',
        '-t',
        'us-central1-docker.pkg.dev/$PROJECT_ID/team-ops-gcp/server:latest',
        '.',
      ]
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'us-central1-docker.pkg.dev/$PROJECT_ID/team-ops-gcp/server:latest',
      ]
