options:
  logging: CLOUD_LOGGING_ONLY
steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-f',
        'dockerfiles/train_model.dockerfile',
        '-t',
        'us-central1-docker.pkg.dev/team-ops-462422/team-ops-gcp/train_model:latest',
        '.',
      ]
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'us-central1-docker.pkg.dev/team-ops-462422/team-ops-gcp/train_model:latest',
      ]
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-f',
        'dockerfiles/predict_model.dockerfile',
        '-t',
        'us-central1-docker.pkg.dev/team-ops-462422/team-ops-gcp/predict_model:latest',
        '.',
      ]
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'us-central1-docker.pkg.dev/team-ops-462422/team-ops-gcp/predict_model:latest',
      ]
