on:
  push:
    branches:
      - main

jobs:
  cml:
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Load checkpoint'
        uses: actions/checkout@v4

      - name: 'Use cml'
        uses: iterative/setup-cml@v1

      - name: 'Setup python'
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: 'Install Dependencies'
        run: |
          pip install .

      - name: 'Training for cml to run'
        run: python team_ops/models/model_cml.py

      - name: 'Write report'
        env:
          REPO_NAME: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cat reports/classification_report.txt >> report.md
          cml-publish reports/figures/confusion_matrix.png --md >> report.md
          cml-send-comment report.md
